// AUTO-GENERATED by tools/keygen/keygen.mjs. Do not edit by hand.
// Regenerate with: npm run keygen:genkey -- --force
export const LICENSE_PUBLIC_KEY_BASE64 = 'MCowBQYDK2VwAyEAnogqM6i6/Lu8CktopXWur5lnPSi4KM4ZDzEAWEUjNHI=';
