#!/usr/bin/env node
/**
 * Ingestra-CaptureStudio vendor keygen CLI (Option A — offline Ed25519 signed keys).
 *
 *   node tools/keygen/keygen.mjs genkey
 *      → Generates an Ed25519 keypair. Writes:
 *           tools/keygen/keys/private.pem        (vendor secret — KEEP OFFLINE)
 *           tools/keygen/keys/public.pem         (printable backup)
 *           src/main/services/license-public-key.ts   (embedded in the app)
 *
 *   node tools/keygen/keygen.mjs issue [opts]
 *      → Signs a license payload and prints a key string.
 *        --tier <pro|team|enterprise|trial>   (default: pro)
 *        --days <N>                            (default: 365)
 *        --id <key id>                         (default: random)
 *        --max <N>                             (default: 1)
 *        --features <f1,f2>                    (default: empty)
 */

import { generateKeyPairSync, sign, createPrivateKey, randomBytes } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, '..', '..');
const KEYS_DIR = join(__dirname, 'keys');
const PRIV_PEM = join(KEYS_DIR, 'private.pem');
const PUB_PEM = join(KEYS_DIR, 'public.pem');
const APP_PUBKEY_TS = join(REPO_ROOT, 'src', 'main', 'services', 'license-public-key.ts');

function ensureDir(p) {
  mkdirSync(p, { recursive: true });
}

function b64url(buf) {
  return Buffer.from(buf).toString('base64').replace(/=+$/g, '').replace(/\+/g, '-').replace(/\//g, '_');
}

function parseArgs(argv) {
  const out = {};
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a.startsWith('--')) {
      const k = a.slice(2);
      const v = argv[i + 1] && !argv[i + 1].startsWith('--') ? argv[++i] : 'true';
      out[k] = v;
    }
  }
  return out;
}

function genkey({ force = false } = {}) {
  ensureDir(KEYS_DIR);
  if (!force && existsSync(PRIV_PEM)) {
    console.error(`Refusing to overwrite existing private key at ${PRIV_PEM}`);
    console.error('Delete it (and back it up first!) or pass --force.');
    process.exit(1);
  }
  const { publicKey, privateKey } = generateKeyPairSync('ed25519');
  writeFileSync(PRIV_PEM, privateKey.export({ format: 'pem', type: 'pkcs8' }), { mode: 0o600 });
  writeFileSync(PUB_PEM, publicKey.export({ format: 'pem', type: 'spki' }));

  const der = publicKey.export({ format: 'der', type: 'spki' });
  const b64 = der.toString('base64');
  const ts = `// AUTO-GENERATED by tools/keygen/keygen.mjs. Do not edit by hand.
// Regenerate with: npm run keygen:genkey -- --force
export const LICENSE_PUBLIC_KEY_BASE64 = '${b64}';
`;
  ensureDir(dirname(APP_PUBKEY_TS));
  writeFileSync(APP_PUBKEY_TS, ts);

  console.log('✓ Ed25519 keypair generated.');
  console.log(`  Private key (KEEP SECRET): ${PRIV_PEM}`);
  console.log(`  Public key (backup):       ${PUB_PEM}`);
  console.log(`  Embedded in app:           ${APP_PUBKEY_TS}`);
  console.log('');
  console.log('Next: issue a test key with:');
  console.log('  npm run keygen:issue -- --tier pro --days 365');
}

function issue(opts) {
  if (!existsSync(PRIV_PEM)) {
    console.error('No private key found. Run `npm run keygen:genkey` first.');
    process.exit(1);
  }
  const tier = String(opts.tier ?? 'pro');
  const days = Number(opts.days ?? 365);
  if (!Number.isFinite(days) || days <= 0) {
    console.error('--days must be a positive number');
    process.exit(1);
  }
  const id = String(opts.id ?? randomBytes(8).toString('hex'));
  const max = opts.max ? Number(opts.max) : 1;
  const features = opts.features
    ? String(opts.features)
        .split(',')
        .map((s) => s.trim())
        .filter(Boolean)
    : undefined;

  const iat = Date.now();
  const exp = iat + days * 24 * 60 * 60 * 1000;
  const payload = { v: 1, id, tier, exp, iat, ...(max ? { max } : {}), ...(features ? { features } : {}) };

  const payloadBytes = Buffer.from(JSON.stringify(payload), 'utf-8');
  const privPem = readFileSync(PRIV_PEM, 'utf-8');
  const privKey = createPrivateKey({ key: privPem, format: 'pem', type: 'pkcs8' });
  const signature = sign(null, payloadBytes, privKey);

  const key = `INGE-${b64url(payloadBytes)}.${b64url(signature)}`;

  console.log('✓ License key issued');
  console.log('  id:      ', id);
  console.log('  tier:    ', tier);
  console.log('  issued:  ', new Date(iat).toISOString());
  console.log('  expires: ', new Date(exp).toISOString());
  console.log('  days:    ', days);
  if (max) console.log('  max:     ', max);
  if (features) console.log('  features:', features.join(','));
  console.log('');
  console.log('Key (paste into the app):');
  console.log(key);
}

const [cmd, ...rest] = process.argv.slice(2);
const args = parseArgs(rest);

switch (cmd) {
  case 'genkey':
    genkey({ force: args.force === 'true' });
    break;
  case 'issue':
    issue(args);
    break;
  default:
    console.log('Usage:');
    console.log('  node tools/keygen/keygen.mjs genkey [--force]');
    console.log('  node tools/keygen/keygen.mjs issue [--tier pro] [--days 365] [--id <id>] [--max N] [--features f1,f2]');
    process.exit(cmd ? 1 : 0);
}
